/**
 * Rwanda Location Data for USSD
 * Provinces → Districts → Sectors
 */

export interface LocationData {
  provinces: Province[];
}

export interface Province {
  name: string;
  nameRw: string;
  nameFr: string;
  districts: District[];
}

export interface District {
  name: string;
  nameRw: string;
  nameFr: string;
  sectors: Sector[];
}

export interface Sector {
  name: string;
  nameRw: string;
  nameFr: string;
}

// Rwanda's 5 Provinces with Districts and Sectors
export const RWANDA_LOCATIONS: LocationData = {
  provinces: [
    {
      name: "Kigali",
      nameRw: "Kigali",
      nameFr: "Kigali",
      districts: [
        {
          name: "Gasabo",
          nameRw: "Gasabo",
          nameFr: "Gasabo",
          sectors: [
            { name: "Bumbogo", nameRw: "Bumbogo", nameFr: "Bumbogo" },
            { name: "Gatsata", nameRw: "Gatsata", nameFr: "Gatsata" },
            { name: "Gikomero", nameRw: "Gikomero", nameFr: "Gikomero" },
            { name: "Gisozi", nameRw: "Gisozi", nameFr: "Gisozi" },
            { name: "Jabana", nameRw: "Jabana", nameFr: "Jabana" },
            { name: "Jali", nameRw: "Jali", nameFr: "Jali" },
            { name: "Kacyiru", nameRw: "Kacyiru", nameFr: "Kacyiru" },
            { name: "Kimihurura", nameRw: "Kimihurura", nameFr: "Kimihurura" },
            { name: "Kimisagara", nameRw: "Kimisagara", nameFr: "Kimisagara" },
            { name: "Kinyinya", nameRw: "Kinyinya", nameFr: "Kinyinya" },
            { name: "Ndera", nameRw: "Ndera", nameFr: "Ndera" },
            { name: "Nduba", nameRw: "Nduba", nameFr: "Nduba" },
            { name: "Remera", nameRw: "Remera", nameFr: "Remera" },
            { name: "Rusororo", nameRw: "Rusororo", nameFr: "Rusororo" },
            { name: "Rutunga", nameRw: "Rutunga", nameFr: "Rutunga" },
          ],
        },
        {
          name: "Kicukiro",
          nameRw: "Kicukiro",
          nameFr: "Kicukiro",
          sectors: [
            { name: "Gahanga", nameRw: "Gahanga", nameFr: "Gahanga" },
            { name: "Gatenga", nameRw: "Gatenga", nameFr: "Gatenga" },
            { name: "Gikondo", nameRw: "Gikondo", nameFr: "Gikondo" },
            { name: "Kagarama", nameRw: "Kagarama", nameFr: "Kagarama" },
            { name: "Kanombe", nameRw: "Kanombe", nameFr: "Kanombe" },
            { name: "Kicukiro", nameRw: "Kicukiro", nameFr: "Kicukiro" },
            { name: "Kigarama", nameRw: "Kigarama", nameFr: "Kigarama" },
            { name: "Masaka", nameRw: "Masaka", nameFr: "Masaka" },
            { name: "Niboye", nameRw: "Niboye", nameFr: "Niboye" },
            { name: "Nyarugunga", nameRw: "Nyarugunga", nameFr: "Nyarugunga" },
          ],
        },
        {
          name: "Nyarugenge",
          nameRw: "Nyarugenge",
          nameFr: "Nyarugenge",
          sectors: [
            { name: "Gitega", nameRw: "Gitega", nameFr: "Gitega" },
            { name: "Kanyinya", nameRw: "Kanyinya", nameFr: "Kanyinya" },
            { name: "Kigali", nameRw: "Kigali", nameFr: "Kigali" },
            { name: "Kimisagara", nameRw: "Kimisagara", nameFr: "Kimisagara" },
            { name: "Mageragere", nameRw: "Mageragere", nameFr: "Mageragere" },
            { name: "Muhima", nameRw: "Muhima", nameFr: "Muhima" },
            { name: "Nyakabanda", nameRw: "Nyakabanda", nameFr: "Nyakabanda" },
            { name: "Nyamirambo", nameRw: "Nyamirambo", nameFr: "Nyamirambo" },
            { name: "Nyarugenge", nameRw: "Nyarugenge", nameFr: "Nyarugenge" },
            { name: "Rwezamenyo", nameRw: "Rwezamenyo", nameFr: "Rwezamenyo" },
          ],
        },
      ],
    },
    {
      name: "Northern",
      nameRw: "Amajyaruguru",
      nameFr: "Nord",
      districts: [
        {
          name: "Burera",
          nameRw: "Burera",
          nameFr: "Burera",
          sectors: [
            { name: "Bungwe", nameRw: "Bungwe", nameFr: "Bungwe" },
            { name: "Butaro", nameRw: "Butaro", nameFr: "Butaro" },
            { name: "Cyanika", nameRw: "Cyanika", nameFr: "Cyanika" },
            { name: "Cyeru", nameRw: "Cyeru", nameFr: "Cyeru" },
            { name: "Gahunga", nameRw: "Gahunga", nameFr: "Gahunga" },
            { name: "Gatebe", nameRw: "Gatebe", nameFr: "Gatebe" },
            { name: "Gitovu", nameRw: "Gitovu", nameFr: "Gitovu" },
            { name: "Kagogo", nameRw: "Kagogo", nameFr: "Kagogo" },
            { name: "Kinoni", nameRw: "Kinoni", nameFr: "Kinoni" },
            { name: "Kinyababa", nameRw: "Kinyababa", nameFr: "Kinyababa" },
            { name: "Kivuye", nameRw: "Kivuye", nameFr: "Kivuye" },
            { name: "Nemba", nameRw: "Nemba", nameFr: "Nemba" },
            { name: "Rugarama", nameRw: "Rugarama", nameFr: "Rugarama" },
            { name: "Rugengabari", nameRw: "Rugengabari", nameFr: "Rugengabari" },
            { name: "Ruhunde", nameRw: "Ruhunde", nameFr: "Ruhunde" },
            { name: "Rusarabuge", nameRw: "Rusarabuge", nameFr: "Rusarabuge" },
            { name: "Rwerere", nameRw: "Rwerere", nameFr: "Rwerere" },
          ],
        },
        {
          name: "Gakenke",
          nameRw: "Gakenke",
          nameFr: "Gakenke",
          sectors: [
            { name: "Busengo", nameRw: "Busengo", nameFr: "Busengo" },
            { name: "Coko", nameRw: "Coko", nameFr: "Coko" },
            { name: "Cyabingo", nameRw: "Cyabingo", nameFr: "Cyabingo" },
            { name: "Gakenke", nameRw: "Gakenke", nameFr: "Gakenke" },
            { name: "Gashenyi", nameRw: "Gashenyi", nameFr: "Gashenyi" },
            { name: "Janja", nameRw: "Janja", nameFr: "Janja" },
            { name: "Kamubuga", nameRw: "Kamubuga", nameFr: "Kamubuga" },
            { name: "Karambo", nameRw: "Karambo", nameFr: "Karambo" },
            { name: "Kivuruga", nameRw: "Kivuruga", nameFr: "Kivuruga" },
            { name: "Mataba", nameRw: "Mataba", nameFr: "Mataba" },
            { name: "Minazi", nameRw: "Minazi", nameFr: "Minazi" },
            { name: "Mugunga", nameRw: "Mugunga", nameFr: "Mugunga" },
            { name: "Muhondo", nameRw: "Muhondo", nameFr: "Muhondo" },
            { name: "Muyongwe", nameRw: "Muyongwe", nameFr: "Muyongwe" },
            { name: "Muzo", nameRw: "Muzo", nameFr: "Muzo" },
            { name: "Nemba", nameRw: "Nemba", nameFr: "Nemba" },
            { name: "Ruli", nameRw: "Ruli", nameFr: "Ruli" },
            { name: "Rusasa", nameRw: "Rusasa", nameFr: "Rusasa" },
            { name: "Rushashi", nameRw: "Rushashi", nameFr: "Rushashi" },
          ],
        },
        {
          name: "Gicumbi",
          nameRw: "Gicumbi",
          nameFr: "Gicumbi",
          sectors: [
            { name: "Bukure", nameRw: "Bukure", nameFr: "Bukure" },
            { name: "Bwisige", nameRw: "Bwisige", nameFr: "Bwisige" },
            { name: "Byumba", nameRw: "Byumba", nameFr: "Byumba" },
            { name: "Cyumba", nameRw: "Cyumba", nameFr: "Cyumba" },
            { name: "Giti", nameRw: "Giti", nameFr: "Giti" },
            { name: "Kageyo", nameRw: "Kageyo", nameFr: "Kageyo" },
            { name: "Kaniga", nameRw: "Kaniga", nameFr: "Kaniga" },
            { name: "Manyagiro", nameRw: "Manyagiro", nameFr: "Manyagiro" },
            { name: "Miyove", nameRw: "Miyove", nameFr: "Miyove" },
            { name: "Mukarange", nameRw: "Mukarange", nameFr: "Mukarange" },
            { name: "Muko", nameRw: "Muko", nameFr: "Muko" },
            { name: "Mutete", nameRw: "Mutete", nameFr: "Mutete" },
            { name: "Nyamiyaga", nameRw: "Nyamiyaga", nameFr: "Nyamiyaga" },
            { name: "Nyankenke", nameRw: "Nyankenke", nameFr: "Nyankenke" },
            { name: "Rubaya", nameRw: "Rubaya", nameFr: "Rubaya" },
            { name: "Rukomo", nameRw: "Rukomo", nameFr: "Rukomo" },
            { name: "Rushaki", nameRw: "Rushaki", nameFr: "Rushaki" },
            { name: "Rutare", nameRw: "Rutare", nameFr: "Rutare" },
            { name: "Ruvune", nameRw: "Ruvune", nameFr: "Ruvune" },
            { name: "Rwamiko", nameRw: "Rwamiko", nameFr: "Rwamiko" },
            { name: "Shangasha", nameRw: "Shangasha", nameFr: "Shangasha" },
          ],
        },
        {
          name: "Musanze",
          nameRw: "Musanze",
          nameFr: "Musanze",
          sectors: [
            { name: "Busogo", nameRw: "Busogo", nameFr: "Busogo" },
            { name: "Cyuve", nameRw: "Cyuve", nameFr: "Cyuve" },
            { name: "Gacaca", nameRw: "Gacaca", nameFr: "Gacaca" },
            { name: "Gashaki", nameRw: "Gashaki", nameFr: "Gashaki" },
            { name: "Gataraga", nameRw: "Gataraga", nameFr: "Gataraga" },
            { name: "Kimonyi", nameRw: "Kimonyi", nameFr: "Kimonyi" },
            { name: "Kinigi", nameRw: "Kinigi", nameFr: "Kinigi" },
            { name: "Muhoza", nameRw: "Muhoza", nameFr: "Muhoza" },
            { name: "Muko", nameRw: "Muko", nameFr: "Muko" },
            { name: "Musanze", nameRw: "Musanze", nameFr: "Musanze" },
            { name: "Nkotsi", nameRw: "Nkotsi", nameFr: "Nkotsi" },
            { name: "Nyange", nameRw: "Nyange", nameFr: "Nyange" },
            { name: "Remera", nameRw: "Remera", nameFr: "Remera" },
            { name: "Rwaza", nameRw: "Rwaza", nameFr: "Rwaza" },
            { name: "Shingiro", nameRw: "Shingiro", nameFr: "Shingiro" },
          ],
        },
        {
          name: "Rulindo",
          nameRw: "Rulindo",
          nameFr: "Rulindo",
          sectors: [
            { name: "Base", nameRw: "Base", nameFr: "Base" },
            { name: "Burega", nameRw: "Burega", nameFr: "Burega" },
            { name: "Bushoki", nameRw: "Bushoki", nameFr: "Bushoki" },
            { name: "Buyoga", nameRw: "Buyoga", nameFr: "Buyoga" },
            { name: "Cyinzuzi", nameRw: "Cyinzuzi", nameFr: "Cyinzuzi" },
            { name: "Cyungo", nameRw: "Cyungo", nameFr: "Cyungo" },
            { name: "Kinihira", nameRw: "Kinihira", nameFr: "Kinihira" },
            { name: "Kisaro", nameRw: "Kisaro", nameFr: "Kisaro" },
            { name: "Masoro", nameRw: "Masoro", nameFr: "Masoro" },
            { name: "Mbogo", nameRw: "Mbogo", nameFr: "Mbogo" },
            { name: "Murambi", nameRw: "Murambi", nameFr: "Murambi" },
            { name: "Ngoma", nameRw: "Ngoma", nameFr: "Ngoma" },
            { name: "Ntarabana", nameRw: "Ntarabana", nameFr: "Ntarabana" },
            { name: "Rukozo", nameRw: "Rukozo", nameFr: "Rukozo" },
            { name: "Rusiga", nameRw: "Rusiga", nameFr: "Rusiga" },
            { name: "Shyorongi", nameRw: "Shyorongi", nameFr: "Shyorongi" },
            { name: "Tumba", nameRw: "Tumba", nameFr: "Tumba" },
          ],
        },
      ],
    },
    {
      name: "Southern",
      nameRw: "Amajyepfo",
      nameFr: "Sud",
      districts: [
        {
          name: "Gisagara",
          nameRw: "Gisagara",
          nameFr: "Gisagara",
          sectors: [
            { name: "Gikonko", nameRw: "Gikonko", nameFr: "Gikonko" },
            { name: "Gishubi", nameRw: "Gishubi", nameFr: "Gishubi" },
            { name: "Kansi", nameRw: "Kansi", nameFr: "Kansi" },
            { name: "Kibilizi", nameRw: "Kibilizi", nameFr: "Kibilizi" },
            { name: "Kigembe", nameRw: "Kigembe", nameFr: "Kigembe" },
            { name: "Mamba", nameRw: "Mamba", nameFr: "Mamba" },
            { name: "Muganza", nameRw: "Muganza", nameFr: "Muganza" },
            { name: "Mugombwa", nameRw: "Mugombwa", nameFr: "Mugombwa" },
            { name: "Mukindo", nameRw: "Mukindo", nameFr: "Mukindo" },
            { name: "Musha", nameRw: "Musha", nameFr: "Musha" },
            { name: "Ndora", nameRw: "Ndora", nameFr: "Ndora" },
            { name: "Nyanza", nameRw: "Nyanza", nameFr: "Nyanza" },
            { name: "Save", nameRw: "Save", nameFr: "Save" },
          ],
        },
        {
          name: "Huye",
          nameRw: "Huye",
          nameFr: "Huye",
          sectors: [
            { name: "Gishamvu", nameRw: "Gishamvu", nameFr: "Gishamvu" },
            { name: "Huye", nameRw: "Huye", nameFr: "Huye" },
            { name: "Karama", nameRw: "Karama", nameFr: "Karama" },
            { name: "Kigoma", nameRw: "Kigoma", nameFr: "Kigoma" },
            { name: "Kinazi", nameRw: "Kinazi", nameFr: "Kinazi" },
            { name: "Mukura", nameRw: "Mukura", nameFr: "Mukura" },
            { name: "Muyira", nameRw: "Muyira", nameFr: "Muyira" },
            { name: "Ntyazo", nameRw: "Ntyazo", nameFr: "Ntyazo" },
            { name: "Nyagisozi", nameRw: "Nyagisozi", nameFr: "Nyagisozi" },
            { name: "Ruhashya", nameRw: "Ruhashya", nameFr: "Ruhashya" },
            { name: "Rusatira", nameRw: "Rusatira", nameFr: "Rusatira" },
            { name: "Rwaniro", nameRw: "Rwaniro", nameFr: "Rwaniro" },
            { name: "Simbi", nameRw: "Simbi", nameFr: "Simbi" },
            { name: "Tumba", nameRw: "Tumba", nameFr: "Tumba" },
          ],
        },
        {
          name: "Kamonyi",
          nameRw: "Kamonyi",
          nameFr: "Kamonyi",
          sectors: [
            { name: "Gacurabwenge", nameRw: "Gacurabwenge", nameFr: "Gacurabwenge" },
            { name: "Karama", nameRw: "Karama", nameFr: "Karama" },
            { name: "Kayenzi", nameRw: "Kayenzi", nameFr: "Kayenzi" },
            { name: "Kayumbu", nameRw: "Kayumbu", nameFr: "Kayumbu" },
            { name: "Mugina", nameRw: "Mugina", nameFr: "Mugina" },
            { name: "Musambira", nameRw: "Musambira", nameFr: "Musambira" },
            { name: "Ngamba", nameRw: "Ngamba", nameFr: "Ngamba" },
            { name: "Nyamiyaga", nameRw: "Nyamiyaga", nameFr: "Nyamiyaga" },
            { name: "Nyarubaka", nameRw: "Nyarubaka", nameFr: "Nyarubaka" },
            { name: "Rugarika", nameRw: "Rugarika", nameFr: "Rugarika" },
            { name: "Rukoma", nameRw: "Rukoma", nameFr: "Rukoma" },
            { name: "Runda", nameRw: "Runda", nameFr: "Runda" },
          ],
        },
        {
          name: "Muhanga",
          nameRw: "Muhanga",
          nameFr: "Muhanga",
          sectors: [
            { name: "Cyeza", nameRw: "Cyeza", nameFr: "Cyeza" },
            { name: "Kabacuzi", nameRw: "Kabacuzi", nameFr: "Kabacuzi" },
            { name: "Kibangu", nameRw: "Kibangu", nameFr: "Kibangu" },
            { name: "Kiyumba", nameRw: "Kiyumba", nameFr: "Kiyumba" },
            { name: "Muhanga", nameRw: "Muhanga", nameFr: "Muhanga" },
            { name: "Mushishiro", nameRw: "Mushishiro", nameFr: "Mushishiro" },
            { name: "Nyabinoni", nameRw: "Nyabinoni", nameFr: "Nyabinoni" },
            { name: "Nyamabuye", nameRw: "Nyamabuye", nameFr: "Nyamabuye" },
            { name: "Nyarusange", nameRw: "Nyarusange", nameFr: "Nyarusange" },
            { name: "Rongi", nameRw: "Rongi", nameFr: "Rongi" },
            { name: "Rugendabari", nameRw: "Rugendabari", nameFr: "Rugendabari" },
            { name: "Shyogwe", nameRw: "Shyogwe", nameFr: "Shyogwe" },
          ],
        },
        {
          name: "Nyamagabe",
          nameRw: "Nyamagabe",
          nameFr: "Nyamagabe",
          sectors: [
            { name: "Buruhukiro", nameRw: "Buruhukiro", nameFr: "Buruhukiro" },
            { name: "Cyanhinda", nameRw: "Cyanhinda", nameFr: "Cyanhinda" },
            { name: "Gasaka", nameRw: "Gasaka", nameFr: "Gasaka" },
            { name: "Gatare", nameRw: "Gatare", nameFr: "Gatare" },
            { name: "Kaduha", nameRw: "Kaduha", nameFr: "Kaduha" },
            { name: "Kamegeli", nameRw: "Kamegeli", nameFr: "Kamegeli" },
            { name: "Kibirizi", nameRw: "Kibirizi", nameFr: "Kibirizi" },
            { name: "Kibumbwe", nameRw: "Kibumbwe", nameFr: "Kibumbwe" },
            { name: "Kitabi", nameRw: "Kitabi", nameFr: "Kitabi" },
            { name: "Mbazi", nameRw: "Mbazi", nameFr: "Mbazi" },
            { name: "Mugano", nameRw: "Mugano", nameFr: "Mugano" },
            { name: "Musange", nameRw: "Musange", nameFr: "Musange" },
            { name: "Musebeya", nameRw: "Musebeya", nameFr: "Musebeya" },
            { name: "Mushubi", nameRw: "Mushubi", nameFr: "Mushubi" },
            { name: "Nkomane", nameRw: "Nkomane", nameFr: "Nkomane" },
            { name: "Tare", nameRw: "Tare", nameFr: "Tare" },
            { name: "Uwinkingi", nameRw: "Uwinkingi", nameFr: "Uwinkingi" },
          ],
        },
        {
          name: "Nyanza",
          nameRw: "Nyanza",
          nameFr: "Nyanza",
          sectors: [
            { name: "Busasamana", nameRw: "Busasamana", nameFr: "Busasamana" },
            { name: "Busoro", nameRw: "Busoro", nameFr: "Busoro" },
            { name: "Cyabakamyi", nameRw: "Cyabakamyi", nameFr: "Cyabakamyi" },
            { name: "Kibilizi", nameRw: "Kibilizi", nameFr: "Kibilizi" },
            { name: "Kigoma", nameRw: "Kigoma", nameFr: "Kigoma" },
            { name: "Mukingo", nameRw: "Mukingo", nameFr: "Mukingo" },
            { name: "Muyira", nameRw: "Muyira", nameFr: "Muyira" },
            { name: "Ntyazo", nameRw: "Ntyazo", nameFr: "Ntyazo" },
            { name: "Nyagisozi", nameRw: "Nyagisozi", nameFr: "Nyagisozi" },
            { name: "Rwabicuma", nameRw: "Rwabicuma", nameFr: "Rwabicuma" },
          ],
        },
        {
          name: "Nyaruguru",
          nameRw: "Nyaruguru",
          nameFr: "Nyaruguru",
          sectors: [
            { name: "Busanze", nameRw: "Busanze", nameFr: "Busanze" },
            { name: "Cyahinda", nameRw: "Cyahinda", nameFr: "Cyahinda" },
            { name: "Kibeho", nameRw: "Kibeho", nameFr: "Kibeho" },
            { name: "Kivu", nameRw: "Kivu", nameFr: "Kivu" },
            { name: "Mata", nameRw: "Mata", nameFr: "Mata" },
            { name: "Muganza", nameRw: "Muganza", nameFr: "Muganza" },
            { name: "Munini", nameRw: "Munini", nameFr: "Munini" },
            { name: "Ngera", nameRw: "Ngera", nameFr: "Ngera" },
            { name: "Ngoma", nameRw: "Ngoma", nameFr: "Ngoma" },
            { name: "Nyabimata", nameRw: "Nyabimata", nameFr: "Nyabimata" },
            { name: "Nyagisozi", nameRw: "Nyagisozi", nameFr: "Nyagisozi" },
            { name: "Nyamagabe", nameRw: "Nyamagabe", nameFr: "Nyamagabe" },
            { name: "Nyamugari", nameRw: "Nyamugari", nameFr: "Nyamugari" },
            { name: "Nyarusange", nameRw: "Nyarusange", nameFr: "Nyarusange" },
            { name: "Sake", nameRw: "Sake", nameFr: "Sake" },
            { name: "Uwacyiza", nameRw: "Uwacyiza", nameFr: "Uwacyiza" },
          ],
        },
        {
          name: "Ruhango",
          nameRw: "Ruhango",
          nameFr: "Ruhango",
          sectors: [
            { name: "Bweramana", nameRw: "Bweramana", nameFr: "Bweramana" },
            { name: "Byimana", nameRw: "Byimana", nameFr: "Byimana" },
            { name: "Kabagali", nameRw: "Kabagali", nameFr: "Kabagali" },
            { name: "Kinazi", nameRw: "Kinazi", nameFr: "Kinazi" },
            { name: "Kinihira", nameRw: "Kinihira", nameFr: "Kinihira" },
            { name: "Mbuye", nameRw: "Mbuye", nameFr: "Mbuye" },
            { name: "Mukura", nameRw: "Mukura", nameFr: "Mukura" },
            { name: "Muyira", nameRw: "Muyira", nameFr: "Muyira" },
            { name: "Ntongwe", nameRw: "Ntongwe", nameFr: "Ntongwe" },
            { name: "Ruhango", nameRw: "Ruhango", nameFr: "Ruhango" },
          ],
        },
      ],
    },
    {
      name: "Eastern",
      nameRw: "Iburasirazuba",
      nameFr: "Est",
      districts: [
        {
          name: "Bugesera",
          nameRw: "Bugesera",
          nameFr: "Bugesera",
          sectors: [
            { name: "Gashora", nameRw: "Gashora", nameFr: "Gashora" },
            { name: "Juru", nameRw: "Juru", nameFr: "Juru" },
            { name: "Kamabuye", nameRw: "Kamabuye", nameFr: "Kamabuye" },
            { name: "Ntarama", nameRw: "Ntarama", nameFr: "Ntarama" },
            { name: "Nyamata", nameRw: "Nyamata", nameFr: "Nyamata" },
            { name: "Nyarugenge", nameRw: "Nyarugenge", nameFr: "Nyarugenge" },
            { name: "Rilima", nameRw: "Rilima", nameFr: "Rilima" },
            { name: "Ruhuha", nameRw: "Ruhuha", nameFr: "Ruhuha" },
            { name: "Rweru", nameRw: "Rweru", nameFr: "Rweru" },
            { name: "Shyara", nameRw: "Shyara", nameFr: "Shyara" },
          ],
        },
        {
          name: "Gatsibo",
          nameRw: "Gatsibo",
          nameFr: "Gatsibo",
          sectors: [
            { name: "Gatsibo", nameRw: "Gatsibo", nameFr: "Gatsibo" },
            { name: "Gitoki", nameRw: "Gitoki", nameFr: "Gitoki" },
            { name: "Kabarore", nameRw: "Kabarore", nameFr: "Kabarore" },
            { name: "Kageyo", nameRw: "Kageyo", nameFr: "Kageyo" },
            { name: "Kiramuruzi", nameRw: "Kiramuruzi", nameFr: "Kiramuruzi" },
            { name: "Kiziguro", nameRw: "Kiziguro", nameFr: "Kiziguro" },
            { name: "Muhura", nameRw: "Muhura", nameFr: "Muhura" },
            { name: "Murambi", nameRw: "Murambi", nameFr: "Murambi" },
            { name: "Ngarama", nameRw: "Ngarama", nameFr: "Ngarama" },
            { name: "Nyagihanga", nameRw: "Nyagihanga", nameFr: "Nyagihanga" },
            { name: "Remera", nameRw: "Remera", nameFr: "Remera" },
            { name: "Rugarama", nameRw: "Rugarama", nameFr: "Rugarama" },
            { name: "Rwimbogo", nameRw: "Rwimbogo", nameFr: "Rwimbogo" },
          ],
        },
        {
          name: "Kayonza",
          nameRw: "Kayonza",
          nameFr: "Kayonza",
          sectors: [
            { name: "Gahini", nameRw: "Gahini", nameFr: "Gahini" },
            { name: "Kabare", nameRw: "Kabare", nameFr: "Kabare" },
            { name: "Kabarondo", nameRw: "Kabarondo", nameFr: "Kabarondo" },
            { name: "Mukarange", nameRw: "Mukarange", nameFr: "Mukarange" },
            { name: "Murama", nameRw: "Murama", nameFr: "Murama" },
            { name: "Murundi", nameRw: "Murundi", nameFr: "Murundi" },
            { name: "Mwiri", nameRw: "Mwiri", nameFr: "Mwiri" },
            { name: "Ndego", nameRw: "Ndego", nameFr: "Ndego" },
            { name: "Nyamirama", nameRw: "Nyamirama", nameFr: "Nyamirama" },
            { name: "Rukara", nameRw: "Rukara", nameFr: "Rukara" },
            { name: "Ruramira", nameRw: "Ruramira", nameFr: "Ruramira" },
            { name: "Rwinkwavu", nameRw: "Rwinkwavu", nameFr: "Rwinkwavu" },
          ],
        },
        {
          name: "Kirehe",
          nameRw: "Kirehe",
          nameFr: "Kirehe",
          sectors: [
            { name: "Gahara", nameRw: "Gahara", nameFr: "Gahara" },
            { name: "Gatore", nameRw: "Gatore", nameFr: "Gatore" },
            { name: "Kigarama", nameRw: "Kigarama", nameFr: "Kigarama" },
            { name: "Kigina", nameRw: "Kigina", nameFr: "Kigina" },
            { name: "Kirehe", nameRw: "Kirehe", nameFr: "Kirehe" },
            { name: "Mahama", nameRw: "Mahama", nameFr: "Mahama" },
            { name: "Mpanga", nameRw: "Mpanga", nameFr: "Mpanga" },
            { name: "Musaza", nameRw: "Musaza", nameFr: "Musaza" },
            { name: "Mushikiri", nameRw: "Mushikiri", nameFr: "Mushikiri" },
            { name: "Nasho", nameRw: "Nasho", nameFr: "Nasho" },
            { name: "Nyamugari", nameRw: "Nyamugari", nameFr: "Nyamugari" },
            { name: "Nyarubuye", nameRw: "Nyarubuye", nameFr: "Nyarubuye" },
          ],
        },
        {
          name: "Ngoma",
          nameRw: "Ngoma",
          nameFr: "Ngoma",
          sectors: [
            { name: "Gashanda", nameRw: "Gashanda", nameFr: "Gashanda" },
            { name: "Jarama", nameRw: "Jarama", nameFr: "Jarama" },
            { name: "Karembo", nameRw: "Karembo", nameFr: "Karembo" },
            { name: "Kazo", nameRw: "Kazo", nameFr: "Kazo" },
            { name: "Kibungo", nameRw: "Kibungo", nameFr: "Kibungo" },
            { name: "Mugesera", nameRw: "Mugesera", nameFr: "Mugesera" },
            { name: "Murama", nameRw: "Murama", nameFr: "Murama" },
            { name: "Mutenderi", nameRw: "Mutenderi", nameFr: "Mutenderi" },
            { name: "Remera", nameRw: "Remera", nameFr: "Remera" },
            { name: "Rukira", nameRw: "Rukira", nameFr: "Rukira" },
            { name: "Sakara", nameRw: "Sakara", nameFr: "Sakara" },
            { name: "Zaza", nameRw: "Zaza", nameFr: "Zaza" },
          ],
        },
        {
          name: "Nyagatare",
          nameRw: "Nyagatare",
          nameFr: "Nyagatare",
          sectors: [
            { name: "Gatunda", nameRw: "Gatunda", nameFr: "Gatunda" },
            { name: "Karama", nameRw: "Karama", nameFr: "Karama" },
            { name: "Karangazi", nameRw: "Karangazi", nameFr: "Karangazi" },
            { name: "Katabagemu", nameRw: "Katabagemu", nameFr: "Katabagemu" },
            { name: "Kiyombe", nameRw: "Kiyombe", nameFr: "Kiyombe" },
            { name: "Matimba", nameRw: "Matimba", nameFr: "Matimba" },
            { name: "Mimuri", nameRw: "Mimuri", nameFr: "Mimuri" },
            { name: "Mukama", nameRw: "Mukama", nameFr: "Mukama" },
            { name: "Musheri", nameRw: "Musheri", nameFr: "Musheri" },
            { name: "Nyagatare", nameRw: "Nyagatare", nameFr: "Nyagatare" },
            { name: "Rukomo", nameRw: "Rukomo", nameFr: "Rukomo" },
            { name: "Rwempasha", nameRw: "Rwempasha", nameFr: "Rwempasha" },
            { name: "Rwimiyaga", nameRw: "Rwimiyaga", nameFr: "Rwimiyaga" },
            { name: "Tabagwe", nameRw: "Tabagwe", nameFr: "Tabagwe" },
          ],
        },
        {
          name: "Rwamagana",
          nameRw: "Rwamagana",
          nameFr: "Rwamagana",
          sectors: [
            { name: "Fumbwe", nameRw: "Fumbwe", nameFr: "Fumbwe" },
            { name: "Gahengeri", nameRw: "Gahengeri", nameFr: "Gahengeri" },
            { name: "Gishari", nameRw: "Gishari", nameFr: "Gishari" },
            { name: "Karenge", nameRw: "Karenge", nameFr: "Karenge" },
            { name: "Kigabiro", nameRw: "Kigabiro", nameFr: "Kigabiro" },
            { name: "Muhazi", nameRw: "Muhazi", nameFr: "Muhazi" },
            { name: "Munyaga", nameRw: "Munyaga", nameFr: "Munyaga" },
            { name: "Munyiginya", nameRw: "Munyiginya", nameFr: "Munyiginya" },
            { name: "Musha", nameRw: "Musha", nameFr: "Musha" },
            { name: "Muyumbu", nameRw: "Muyumbu", nameFr: "Muyumbu" },
            { name: "Mwulire", nameRw: "Mwulire", nameFr: "Mwulire" },
            { name: "Nyakaliro", nameRw: "Nyakaliro", nameFr: "Nyakaliro" },
            { name: "Nzige", nameRw: "Nzige", nameFr: "Nzige" },
            { name: "Rubona", nameRw: "Rubona", nameFr: "Rubona" },
            { name: "Rukoma", nameRw: "Rukoma", nameFr: "Rukoma" },
            { name: "Rusarabuye", nameRw: "Rusarabuye", nameFr: "Rusarabuye" },
            { name: "Rwamagana", nameRw: "Rwamagana", nameFr: "Rwamagana" },
          ],
        },
      ],
    },
    {
      name: "Western",
      nameRw: "Iburengerazuba",
      nameFr: "Ouest",
      districts: [
        {
          name: "Karongi",
          nameRw: "Karongi",
          nameFr: "Karongi",
          sectors: [
            { name: "Bwishyura", nameRw: "Bwishyura", nameFr: "Bwishyura" },
            { name: "Gashari", nameRw: "Gashari", nameFr: "Gashari" },
            { name: "Gishyita", nameRw: "Gishyita", nameFr: "Gishyita" },
            { name: "Gitesi", nameRw: "Gitesi", nameFr: "Gitesi" },
            { name: "Mubuga", nameRw: "Mubuga", nameFr: "Mubuga" },
            { name: "Murambi", nameRw: "Murambi", nameFr: "Murambi" },
            { name: "Murundi", nameRw: "Murundi", nameFr: "Murundi" },
            { name: "Mutuntu", nameRw: "Mutuntu", nameFr: "Mutuntu" },
            { name: "Rubengera", nameRw: "Rubengera", nameFr: "Rubengera" },
            { name: "Rugabano", nameRw: "Rugabano", nameFr: "Rugabano" },
            { name: "Ruganda", nameRw: "Ruganda", nameFr: "Ruganda" },
            { name: "Rwankuba", nameRw: "Rwankuba", nameFr: "Rwankuba" },
            { name: "Twumba", nameRw: "Twumba", nameFr: "Twumba" },
          ],
        },
        {
          name: "Ngororero",
          nameRw: "Ngororero",
          nameFr: "Ngororero",
          sectors: [
            { name: "Bwira", nameRw: "Bwira", nameFr: "Bwira" },
            { name: "Gatumba", nameRw: "Gatumba", nameFr: "Gatumba" },
            { name: "Hindiro", nameRw: "Hindiro", nameFr: "Hindiro" },
            { name: "Kabaya", nameRw: "Kabaya", nameFr: "Kabaya" },
            { name: "Kageyo", nameRw: "Kageyo", nameFr: "Kageyo" },
            { name: "Kavumu", nameRw: "Kavumu", nameFr: "Kavumu" },
            { name: "Matyazo", nameRw: "Matyazo", nameFr: "Matyazo" },
            { name: "Muhanda", nameRw: "Muhanda", nameFr: "Muhanda" },
            { name: "Muhororo", nameRw: "Muhororo", nameFr: "Muhororo" },
            { name: "Ndaro", nameRw: "Ndaro", nameFr: "Ndaro" },
            { name: "Ngororero", nameRw: "Ngororero", nameFr: "Ngororero" },
            { name: "Nyange", nameRw: "Nyange", nameFr: "Nyange" },
            { name: "Sovu", nameRw: "Sovu", nameFr: "Sovu" },
          ],
        },
        {
          name: "Nyabihu",
          nameRw: "Nyabihu",
          nameFr: "Nyabihu",
          sectors: [
            { name: "Bigogwe", nameRw: "Bigogwe", nameFr: "Bigogwe" },
            { name: "Jenda", nameRw: "Jenda", nameFr: "Jenda" },
            { name: "Jomba", nameRw: "Jomba", nameFr: "Jomba" },
            { name: "Kabatwa", nameRw: "Kabatwa", nameFr: "Kabatwa" },
            { name: "Karago", nameRw: "Karago", nameFr: "Karago" },
            { name: "Kintobo", nameRw: "Kintobo", nameFr: "Kintobo" },
            { name: "Mukamira", nameRw: "Mukamira", nameFr: "Mukamira" },
            { name: "Muringa", nameRw: "Muringa", nameFr: "Muringa" },
            { name: "Rambura", nameRw: "Rambura", nameFr: "Rambura" },
            { name: "Rugera", nameRw: "Rugera", nameFr: "Rugera" },
            { name: "Rurembo", nameRw: "Rurembo", nameFr: "Rurembo" },
            { name: "Shyira", nameRw: "Shyira", nameFr: "Shyira" },
          ],
        },
        {
          name: "Nyamasheke",
          nameRw: "Nyamasheke",
          nameFr: "Nyamasheke",
          sectors: [
            { name: "Bushekeri", nameRw: "Bushekeri", nameFr: "Bushekeri" },
            { name: "Bushenge", nameRw: "Bushenge", nameFr: "Bushenge" },
            { name: "Cyato", nameRw: "Cyato", nameFr: "Cyato" },
            { name: "Gihombo", nameRw: "Gihombo", nameFr: "Gihombo" },
            { name: "Kagano", nameRw: "Kagano", nameFr: "Kagano" },
            { name: "Kanjongo", nameRw: "Kanjongo", nameFr: "Kanjongo" },
            { name: "Karambi", nameRw: "Karambi", nameFr: "Karambi" },
            { name: "Karengera", nameRw: "Karengera", nameFr: "Karengera" },
            { name: "Kirimbi", nameRw: "Kirimbi", nameFr: "Kirimbi" },
            { name: "Macuba", nameRw: "Macuba", nameFr: "Macuba" },
            { name: "Mahembe", nameRw: "Mahembe", nameFr: "Mahembe" },
            { name: "Nyabiteke", nameRw: "Nyabiteke", nameFr: "Nyabiteke" },
            { name: "Rangiro", nameRw: "Rangiro", nameFr: "Rangiro" },
            { name: "Ruharambuga", nameRw: "Ruharambuga", nameFr: "Ruharambuga" },
            { name: "Shangi", nameRw: "Shangi", nameFr: "Shangi" },
            { name: "Tyazo", nameRw: "Tyazo", nameFr: "Tyazo" },
          ],
        },
        {
          name: "Rubavu",
          nameRw: "Rubavu",
          nameFr: "Rubavu",
          sectors: [
            { name: "Bugeshi", nameRw: "Bugeshi", nameFr: "Bugeshi" },
            { name: "Busasamana", nameRw: "Busasamana", nameFr: "Busasamana" },
            { name: "Cyanzarwe", nameRw: "Cyanzarwe", nameFr: "Cyanzarwe" },
            { name: "Gisenyi", nameRw: "Gisenyi", nameFr: "Gisenyi" },
            { name: "Kanama", nameRw: "Kanama", nameFr: "Kanama" },
            { name: "Kanzenze", nameRw: "Kanzenze", nameFr: "Kanzenze" },
            { name: "Mudende", nameRw: "Mudende", nameFr: "Mudende" },
            { name: "Nyakiriba", nameRw: "Nyakiriba", nameFr: "Nyakiriba" },
            { name: "Nyamyumba", nameRw: "Nyamyumba", nameFr: "Nyamyumba" },
            { name: "Nyundo", nameRw: "Nyundo", nameFr: "Nyundo" },
            { name: "Rubavu", nameRw: "Rubavu", nameFr: "Rubavu" },
            { name: "Rugerero", nameRw: "Rugerero", nameFr: "Rugerero" },
          ],
        },
        {
          name: "Rutsiro",
          nameRw: "Rutsiro",
          nameFr: "Rutsiro",
          sectors: [
            { name: "Boneza", nameRw: "Boneza", nameFr: "Boneza" },
            { name: "Gihango", nameRw: "Gihango", nameFr: "Gihango" },
            { name: "Kigeyo", nameRw: "Kigeyo", nameFr: "Kigeyo" },
            { name: "Kivumu", nameRw: "Kivumu", nameFr: "Kivumu" },
            { name: "Manihira", nameRw: "Manihira", nameFr: "Manihira" },
            { name: "Mukura", nameRw: "Mukura", nameFr: "Mukura" },
            { name: "Murunda", nameRw: "Murunda", nameFr: "Murunda" },
            { name: "Musasa", nameRw: "Musasa", nameFr: "Musasa" },
            { name: "Mushonyi", nameRw: "Mushonyi", nameFr: "Mushonyi" },
            { name: "Mushubati", nameRw: "Mushubati", nameFr: "Mushubati" },
            { name: "Nyabirasi", nameRw: "Nyabirasi", nameFr: "Nyabirasi" },
            { name: "Ruhango", nameRw: "Ruhango", nameFr: "Ruhango" },
            { name: "Rusebeya", nameRw: "Rusebeya", nameFr: "Rusebeya" },
          ],
        },
        {
          name: "Rusizi",
          nameRw: "Rusizi",
          nameFr: "Rusizi",
          sectors: [
            { name: "Bugarama", nameRw: "Bugarama", nameFr: "Bugarama" },
            { name: "Butare", nameRw: "Butare", nameFr: "Butare" },
            { name: "Bweyeye", nameRw: "Bweyeye", nameFr: "Bweyeye" },
            { name: "Gihundwe", nameRw: "Gihundwe", nameFr: "Gihundwe" },
            { name: "Gihundwe", nameRw: "Gihundwe", nameFr: "Gihundwe" },
            { name: "Giheke", nameRw: "Giheke", nameFr: "Giheke" },
            { name: "Gihundwe", nameRw: "Gihundwe", nameFr: "Gihundwe" },
            { name: "Kamembe", nameRw: "Kamembe", nameFr: "Kamembe" },
            { name: "Muganza", nameRw: "Muganza", nameFr: "Muganza" },
            { name: "Mururu", nameRw: "Mururu", nameFr: "Mururu" },
            { name: "Nkanka", nameRw: "Nkanka", nameFr: "Nkanka" },
            { name: "Nkombo", nameRw: "Nkombo", nameFr: "Nkombo" },
            { name: "Nkungu", nameRw: "Nkungu", nameFr: "Nkungu" },
            { name: "Nyakabuye", nameRw: "Nyakabuye", nameFr: "Nyakabuye" },
            { name: "Nyakarenzo", nameRw: "Nyakarenzo", nameFr: "Nyakarenzo" },
            { name: "Nzahaha", nameRw: "Nzahaha", nameFr: "Nzahaha" },
            { name: "Rwimbogo", nameRw: "Rwimbogo", nameFr: "Rwimbogo" },
          ],
        },
      ],
    },
  ],
};

// Helper functions
export function getProvinces(language: 'rw' | 'en' | 'fr' = 'en'): string[] {
  return RWANDA_LOCATIONS.provinces.map((p) => {
    if (language === 'rw') return p.nameRw;
    if (language === 'fr') return p.nameFr;
    return p.name;
  });
}

export function getDistrictsForProvince(provinceIndex: number, language: 'rw' | 'en' | 'fr' = 'en'): string[] {
  const province = RWANDA_LOCATIONS.provinces[provinceIndex];
  if (!province) return [];
  return province.districts.map((d) => {
    if (language === 'rw') return d.nameRw;
    if (language === 'fr') return d.nameFr;
    return d.name;
  });
}

export function getSectorsForDistrict(provinceIndex: number, districtIndex: number, language: 'rw' | 'en' | 'fr' = 'en'): string[] {
  const province = RWANDA_LOCATIONS.provinces[provinceIndex];
  if (!province) return [];
  const district = province.districts[districtIndex];
  if (!district) return [];
  return district.sectors.map((s) => {
    if (language === 'rw') return s.nameRw;
    if (language === 'fr') return s.nameFr;
    return s.name;
  });
}

export function getLocationName(provinceIndex: number, districtIndex: number, sectorIndex: number, language: 'rw' | 'en' | 'fr' = 'en'): { province: string; district: string; sector: string } {
  const province = RWANDA_LOCATIONS.provinces[provinceIndex];
  if (!province) throw new Error('Invalid province index');
  const district = province.districts[districtIndex];
  if (!district) throw new Error('Invalid district index');
  const sector = district.sectors[sectorIndex];
  if (!sector) throw new Error('Invalid sector index');

  return {
    province: language === 'rw' ? province.nameRw : language === 'fr' ? province.nameFr : province.name,
    district: language === 'rw' ? district.nameRw : language === 'fr' ? district.nameFr : district.name,
    sector: language === 'rw' ? sector.nameRw : language === 'fr' ? sector.nameFr : sector.name,
  };
}
